name: PlayerFly
version: "${version}"
main: org.hwabeag.playerfly.PlayerFlyPlugin
api-version: "1.21"
authors: [hwabeag]
softdepend: [PlaceholderAPI]

commands:
  playerfly:
    description: 플라이 시간을 관리합니다.
    usage: /playerfly
    aliases: [플라이관리, fly]
  flyticket:
    description: 플라이권 아이템을 지급합니다.
    usage: /flyticket 지급 <닉네임> [분]
    aliases: [플라이권, fly권]
